Implement image transfer function
lemoncloud-io/lemon-hello-api pull request #41
Opened 2022-10-27 08:36 UTC by baedonguri

과제 PR 제출합니다.

2022-10-27 08:56 UTC, steve-lemon reviewed
전반적으로 코드의 가독성을 높이도록 개선해 봅시다.

2022-10-27 08:56 UTC, steve-lemon commented on .prettierignore
> +*.spec.ts
`spec.ts` 파일도 적용 대상되어야함

2022-10-27 08:56 UTC, steve-lemon commented on src/api/hello-api.ts
> +    // written by aiden
함수 코멘트는 `/*  */` 이용해줘요

2022-10-27 08:56 UTC, steve-lemon commented on src/service/hello-dummies.ts
> +        if (!['dog', 'cat'].includes(animal)) throw new Error(`ERR! ${animal} keywords are not supported.`);
유저 입력값 체크는 별도로 해주고, 여기서는 type 정의로 개선해줘요
또한, 파라미티 검증은 아래와 같은 형식으로 해줘요.
`@animal (string) is invalid - ${animal} are not supported`

2022-10-27 08:56 UTC, steve-lemon commented on src/service/hello-service-aiden.spec.ts
> +            text : `Hello lemon! - ${date.getHours()}:${date.getMinutes()}`
시간 이용시, 내부에서 이용한 Date와 테스트 환경의 Date가 다를 경우가 있음 고려

2022-10-27 08:56 UTC, steve-lemon commented on src/service/hello-service.ts
> +                    _log(message);
`_log` 이용시, NS 를 꼭 넣어서 이용해줘요.
ex) _log(NS, ` message =`, message)

2022-10-27 08:56 UTC, steve-lemon commented on src/service/hello-service.ts
> +        if (typeof message !== 'object') throw new Error('!ERR Failed to load json file.');
에러 테스트 포맷 변경 필요

2022-10-27 08:56 UTC, steve-lemon commented on src/service/hello-service.ts
> +        let targetUrl = `https://api.the${animal}api.com/v1/images/search`;
`let` 보다는 `const` 가 맞아보임

2022-10-27 08:56 UTC, steve-lemon commented on src/service/hello-service.ts
> +        let options: any = url.parse(targetUrl);
마찬가지 `const` 이용과 타입 정의해 주면 좋을듯.

2022-10-27 08:56 UTC, steve-lemon commented on src/service/hello-service.ts
> +    public getRandomImage = async (animal: string = 'cat'): Promise<PostResponse> => {
1. 이 함수의 comment 정의가 있어야할듯
2. 입력 파라미터는 타입정의와 입력 검증을 분리하면 좋을듯
3. 함수를 2단계로 구분가능해 보임 ( 타겟 URL구하기와 이미지 로딩)
4. PostResponse 타입보다는 좀더 단순화된 리턴값이 좋음.

2022-10-31 01:43 UTC, baedonguri commented on src/service/hello-service.ts
> +        if (typeof message !== 'object') throw new Error('!ERR Failed to load json file.');
loadJsonSync()의 경우, 성공 시 json파일을 object 형태로 반환하고,
실패할 경우 string 형태의 message를 반환하는 형태로 이해하여
테스트 코드 작성 시 해당 포맷으로 설정 하였는데 어떤 방식으로 체크하면 더 좋은 코드가 
될 수 있을지 여쭤봐도 괜찮을까요?

2022-11-01 11:48 UTC, steve-lemon requested changes
마지막으로, 코멘트 및 함수 이름 정리로 마무리합시다.

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +        if (typeof message !== 'object') throw new Error('!ERR Failed to load json file.');
@see `lemon-core/mxNextFailure`

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +            throw new Error(`@image url (string) is invalid - ${imageUrl} are not supported`);
recommended error text
`.imageUrl[${imageUrl}] (string) is invalid - not supported`

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +            throw new Error(`@animal (string) is invalid - ${keyword} are not supported`);
recommended error text
`.keyword[${keyword}](string) is invalid - not supported`

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +        const keyword = body.keyword ? body.keyword : 'cat';
const keyword = $T.S(body?.keyword, 'cat');

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +    public determinePostDirectly = (id: any, param: any) => {
`any` 사용은 안하도록

2022-11-01 11:48 UTC, steve-lemon commented on .prettierignore
> +*.spec.ts
spec 도 prettier 먹도록.

2022-11-01 11:48 UTC, steve-lemon commented on env/lemon.yml
> +    LS: 0 # log silence.
이 파일은 단순 indent 변경같은데, 원본으로 복원해줘유.

2022-11-01 11:48 UTC, steve-lemon commented on src/api/hello-api.ts
> +    public getHelloTime: NextHandler = async (id: any, param: any, body: any, ctx: any) => {
1. comment 이 적정하게 달아주고, 샘플도 같이 적어주면 좋을듯.
2. 파라미터들 (ex: id, param, body, ctx)은 `NextHandler` 템플릿으로 지정가능함.

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service-aiden.spec.ts
> + * @author Aiden
1. history 입력 날짜별로 잘 넣어주고
2. 카피라이트 문구도 추가해줘유.

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +export interface ImageInfo {
여기도 타입 정보 설명(코멘트) 추가

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +    public determinePostDirectly = (id: string, param: any): [string, boolean] => {
여기도, 함수 설명(코멘트) 추가

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +    public makeSlackBody = async (url: string): Promise<SlackPostBody> => {
여기도, 함수 설명(코멘트) 추가

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +    public getRandomImage = async (imageInfo: ImageInfo): Promise<string> => {
외부에서 리소스를 가져올때는 fetch 라는 이름으로 써줘유.
그래서 `fetchRandomImageUrl()` 이렇게 하면 더 좋을듯

2022-11-01 11:48 UTC, steve-lemon commented on src/service/hello-service.ts
> +    public checkImageKeyword = (body: any): ImageInfo => {
이렇게, 단순 입/출력 변환 같은경우 함수 이름을 `as`로 써줘유 (단, async 아님)
즉, `asImageInfo()` 이렇게 해주면 좋을듯.

2022-11-02 02:29 UTC, steve-lemon approved these changes

2022-11-02 02:30 UTC, merged

2022-11-02 02:30 UTC, steve-lemon commented
LGTM